Repository PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2, pull requests merged in 2022-03, with the labels that each got.

#46 added total and avg reviews
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/SpecificFoodLeisure.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Home/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/images/DefaultR.jpeg
Labels: enhancement, SIT_ICT2106_p3-06

#59 P3 6 feature landing page
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/HomeController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/FoodLeisureServices/FoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/FoodLeisureServices/IFoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/images/DefaultR.jpeg
Labels: SIT_ICT2106_p3-06, Development

#60 P3 6 feature admin featured food leisure
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FeaturedFoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/ConciergeContext.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/FoodLeisureServices/FoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/GenericRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/FoodLeisureServices/FoodLeisure.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/FoodLeisureServices/IFoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Startup.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FeaturedFoodLeisure/Admin_AddFeaturedFoodLeisure.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/FeaturedFoodLeisure/Create.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/FeaturedFoodLeisure/Edit.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/appsettings.json
Labels: SIT_ICT2106_p3-06, Development

#68 some images uploaded
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/images/DefaultHawker.jpeg
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/images/DefaultPoi.jpg
Labels: enhancement, SIT_ICT2106_p3-06

#73 added banner to landing page
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/FoodLeisureServices/FoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/featuredFoodLeisure.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
Labels: enhancement

#94 Blog feature
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/BlogController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/Itineraries/ItineraryItem.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Itineraries/IItineraryItemRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/Blog/Blog.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Blog/BlogList.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
Labels: Development

#102 added reviews for business owner to reply to
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/BlogController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/HomeController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/TransportationController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/ConciergeContext.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/FoodLeisureServices/FoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/Itineraries/BlogRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/OtherServices/ReviewRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/OtherServices/TransportFaresRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/OtherServices/TransportationRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/BusinessReview.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/IReview.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/NormalReview.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/Review.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/ReviewFactory.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/FoodLeisureServices/IFoodLeisureRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/Itineraries/IBlogRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/OtherServices/IReviewRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/OtherServices/ITransportFaresRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/OtherServices/ITransportationRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/SpecificFoodLeisure.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Home/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/images/PFP5.webp
Labels: SIT_ICT2106_p3-06, Development

#110 sorted a review
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/Context.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/IStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SortRatingsStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SortReviewDateStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SortReviewIDStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/SpecificFoodLeisure.cshtml
Labels: Development

#114 added search into strategy pattern as Prof indri say too simple
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Data/OtherServices/ReviewRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/Context.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/IStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SearchSortDescriptionStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SearchSortRatingsStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SearchSortReviewDateStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SearchSortReviewIDStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SortRatingsStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SortReviewDateStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SortReviewIDStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Interfaces/OtherServices/IReviewRepo.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/FoodLeisure/SpecificFoodLeisure.cshtml
Labels: Development
