Repository PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2, pull requests merged in 2022-04, with the labels that each got.

#125 P3 2 feature list attractions
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/AttractionController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/HomeController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/Attraction/Attraction.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/Privacy.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/ViewDetails.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
Labels: SIT_ICT2106_p3-02, Development

#126 P3 2 feature list attractions
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/AttractionController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/HomeController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/Attraction/Attraction.cs
  personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/Privacy.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Attraction/ViewDetails.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
Labels: SIT_ICT2106_p3-02, Development

#128 Merging from P3-3_SearchFeature to P3-3_Itinerary
  personalised_conceirge_m2/personalised_concierge_m1/Views/Itinerary/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/Views/Shared/_Layout.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/assets/js/data-tables.js
Labels: SIT_ICT2106_p3-03, Development

#131 Merging Branch P3-3_SearchFeature to P3-3_Dev
  personalised_conceirge_m2/personalised_concierge_m1/Views/Itinerary/Index.cshtml
  personalised_conceirge_m2/personalised_concierge_m1/wwwroot/assets/js/data-tables.js
Labels: enhancement, SIT_ICT2106_p3-03, Development

#132 refactoring
  personalised_conceirge_m2/personalised_concierge_m1/Controllers/FoodLeisureController.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/Context.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/FilterSortDescriptionStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/FilterSortRatingsStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/FilterSortReviewDateStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/IStrategy.cs
  personalised_conceirge_m2/personalised_concierge_m1/Models/Entities/OtherServices/SearchSortReviewIDStrategy.cs
Labels: Development
